### ISSUE TITLE
stay in the font-size mode until asked to leave it

### ISSUE THREAD

**Issue by cyboflash** [drmikehenry/vim-fontsize#5]
Is it possible to introduce the following enhancement

Instead of using a timeout value, simply stay in the font-size mode until asked to leave it.

example:
execute command to get into the font-size mode
modify font size to one's liking
execute command to exit font-size mode

[vim-submode](http://www.vim.org/scripts/script.php?script_id=2467) could be useful in creating this mode

**Comment by drmikehenry** [comment]
I can see why it would be useful to have separate values for the fontsize key timeout and Vim's overall timeout value.  I'll give this some investigation.

**Comment by drmikehenry** [comment]
I've released version 0.4.0 with the ability to configure the time-out settings independently from Vim's 'timeout' and 'timeoutlen', inspired by the implementation of Kana's vim-submode plugin.  The following line in your ```.vimrc``` will disable the time-out feature:
```VimL
let g:fontsize#timeout = 0
```

**Comment by cyboflash** [comment]
Thanks. It seems to be working. I really appreciate reworking this.

**Comment by drmikehenry** [comment]
Great - I'm glad it's working for you :-)
