### ISSUE TITLE
Support for GTK3

### ISSUE THREAD

**Issue by monyxie** [drmikehenry/vim-fontsize#7]
The plugin is not working with gVim compiled with GTK3 GUI.
The gVim is compiled from official v8.0 source. 
`:version` shows: `Huge version with GTK3 GUI.`
`:echo has('gui_gtk2')` shows `0`.
`:echo has('gui_gtk3')` shows `1`.

**Comment by drmikehenry** [comment]
I hadn't tried GTK3 yet; thanks for letting me know.  I've released version 0.4.1 which adds support for gui_gtk3.
