### ISSUE TITLE
Key names in the readme are misleading

### ISSUE THREAD

**Issue by Chiel92** [drmikehenry/vim-fontsize#8]
After reading the readme

> For example, using the default key bindings, pressing <Leader><Leader>+ will enter "font size" mode and increase the font size by one. Once in the mode, pressing the "+" key repeatedly will increase the font size by one for each additional press.

pressing `<leader><leader>+` did not get me into this special mode. Instead it only zoomed in once.
After having looked at the .vim source code it became clear that you actually have to press `<leader><leader>=` ! I would strongly recommend adjusting this in the readme to avoid any future confusion for other users.

**Comment by drmikehenry** [comment]
Everything works as documented for me.  All of the mappings that change the font size enter font size mode.  Some, like ``<Leader><Leader>+``, modify the font size and then enter the mode, whereas ``<Leader><Leader>=`` exists to enter font size mode without first changing the font size.  Perhaps something in your overall Vim configuration causes different behavior for you.  You might want to try commenting out parts of your configuration or temporarily moving your ``~/.vim`` directory out of the way and running the plugin in a clean configuration to help diagnose what's going wrong.
