### ISSUE TITLE
Bug: plugin pastes <SNR>56_(fontsize) when mapped with imap

### ISSUE THREAD

**Issue by Millani** [drmikehenry/vim-fontsize#9]
I tried to create the following mappings for gvim:

```
imap <kPlus> <C-o><Plug>FontsizeInc<CR>
imap <kMinus> <C-o><Plug>FontsizeDec<CR>
```

They indeed do the expected, that is, they increase and decrease the font size when in Input mode. However, they also paste the following wherever the cursor happens to be:

`<SNR>56_(fontsize)`

Is there a workaround to that?

**Comment by drmikehenry** [comment]
You might try either of the following pairs of imaps.  The first pair temporarily inserts a letter `x`, then exits insert mode, performs the desired operation, then begins a substitute operation via `s` to remove the `x` and re-enter insert mode.  This leaves your cursor where it was, but it does have some visual flashing as the `x` is inserted and removed.  The second pair does not insert and then remove any characters, so it may have less flashing; however, if the cursor begins at the start of a non-empty line, it will move over one position as a side-effect of the mappings.  Here are the pairs of mappings you might try:
```viml
imap <kPlus> x<Esc><Plug>FontsizeInc<CR>s
imap <kMinus> x<Esc><Plug>FontsizeDec<CR>s

imap <kPlus> <Esc><Plug>FontsizeInc<CR>a
imap <kMinus> <Esc><Plug>FontsizeDec<CR>a
```

**Comment by drmikehenry** [comment]
You're welcome :-)
